external_components:
  - source: github://Brokly/esphome_aux_ac_component
    components: [ aux_ac ]
    refresh: 0s

esphome:
  name: aux_air_conditioner
  platform: ESP8266
  board: esp12e

# don't forget to set your's wifi settings!
wifi:
  ssid: "WIFI SSID"
  password: "seCRETpassWORD"
  manual_ip:
    static_ip: 192.168.0.2
    gateway: 192.168.0.1
    subnet: 255.255.255.0
  ap:
    ssid: AUX Hotspot
    password: "seCREThotSPOTpassWORD"

captive_portal:
debug:

logger:
    level: DEBUG
    baud_rate: 0

api:

ota:

# UART0 configuration for AUX air conditioner communication
uart:
  id: ac_uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 4800
  data_bits: 8
  parity: EVEN
  stop_bits: 1

climate:
  - platform: aux_ac
    name: "AC Name"
